//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class UniversityDetail
    {
        public int ID { get; set; }
        public Nullable<double> UNITID { get; set; }
        public string INSTNM { get; set; }
        public string ADDR { get; set; }
        public string CITY { get; set; }
        public string STABBR { get; set; }
        public string ZIP { get; set; }
        public Nullable<double> FIPS { get; set; }
        public Nullable<double> OBEREG { get; set; }
        public string CHFNM { get; set; }
        public string CHFTITLE { get; set; }
        public Nullable<double> GENTELE { get; set; }
        public Nullable<double> FAXTELE { get; set; }
        public Nullable<double> EIN { get; set; }
        public Nullable<double> OPEID { get; set; }
        public Nullable<double> OPEFLAG { get; set; }
        public string WEBADDR { get; set; }
        public string ADMINURL { get; set; }
        public string FAIDURL { get; set; }
        public string NPRICURL { get; set; }
        public Nullable<double> SECTOR { get; set; }
        public Nullable<double> ICLEVEL { get; set; }
        public Nullable<double> CONTROL { get; set; }
        public Nullable<double> HLOFFER { get; set; }
        public Nullable<double> UGOFFER { get; set; }
        public Nullable<double> GROFFER { get; set; }
        public Nullable<double> HDEGOFR1 { get; set; }
        public Nullable<double> DEGGRANT { get; set; }
        public Nullable<double> HBCU { get; set; }
        public Nullable<double> HOSPITAL { get; set; }
        public Nullable<double> MEDICAL { get; set; }
        public Nullable<double> TRIBAL { get; set; }
        public Nullable<double> LOCALE { get; set; }
        public Nullable<double> OPENPUBL { get; set; }
        public string ACT { get; set; }
        public Nullable<double> NEWID { get; set; }
        public Nullable<double> DEATHYR { get; set; }
        public Nullable<double> CLOSEDAT { get; set; }
        public Nullable<double> CYACTIVE { get; set; }
        public Nullable<double> POSTSEC { get; set; }
        public Nullable<double> PSEFLAG { get; set; }
        public Nullable<double> PSET4FLG { get; set; }
        public Nullable<double> RPTMTH { get; set; }
        public string IALIAS { get; set; }
        public Nullable<double> INSTCAT { get; set; }
        public Nullable<double> CCBASIC { get; set; }
        public Nullable<double> CCIPUG { get; set; }
        public Nullable<double> CCIPGRAD { get; set; }
        public Nullable<double> CCUGPROF { get; set; }
        public Nullable<double> CCENRPRF { get; set; }
        public Nullable<double> CCSIZSET { get; set; }
        public Nullable<double> CARNEGIE { get; set; }
        public Nullable<double> LANDGRNT { get; set; }
        public Nullable<double> INSTSIZE { get; set; }
        public Nullable<double> CBSA { get; set; }
        public Nullable<double> CBSATYPE { get; set; }
        public Nullable<double> CSA { get; set; }
        public Nullable<double> NECTA { get; set; }
        public Nullable<double> F1SYSTYP { get; set; }
        public string F1SYSNAM { get; set; }
        public Nullable<double> F1SYSCOD { get; set; }
        public Nullable<double> COUNTYCD { get; set; }
        public string COUNTYNM { get; set; }
        public Nullable<double> CNGDSTCD { get; set; }
        public Nullable<double> LONGITUD { get; set; }
        public Nullable<double> LATITUDE { get; set; }
    }
}
